REQUIREMENTPATH = ./anforderungen
CONCEPTPATH = ./konzept
RESEARCHPATH = ./recherche


.PHONY: all requirement concept research

all: requirement concept research

requirement:
	cd $(REQUIREMENTPATH)/;	make doc;

concept:
	cd $(CONCEPTPATH)/; make doc;

research:
	cd $(RESEARCHPATH)/; make doc;
